siaikaisihantei Close#10
Chaha1n/Shugiou-Client pull request #13
Opened 2021-12-25 12:58 UTC by plmwa

違うユーザーがサーバーにアクセスしていたらvalueの値が反映されるように変更しました。
環境変数とinputする変数の名前がどちらともuser_nameになっていたので修正しました。

2021-12-25 13:11 UTC, Chaha1n requested changes
これは？と思うところがいくつかあったので、ちょっと修正ポイントを書きました。
よろしくお願いします！

2021-12-25 13:11 UTC, Chaha1n commented on main.py
>  client_id=""
この変数要りますかね？空文字のまま特に更新されていないので、53行目で直接空文字を渡せば良いかなと。
(プレイヤー名を使ってクライアントごとに一意にする、みたいな値だった気がしますが)

2021-12-25 13:11 UTC, Chaha1n commented on main.py
> +    if player_name!=eval(msg.payload.decode())["name"]:
このeval()はどういう意図ですかね...?
文字列をコードとして解釈する、特にユーザーの入力をそうするのは非常に大きなセキュリティリスクがあるので、可能な限りやらない、やるとしても本当なら適切にエスケープ処理するなどしてからやるべきかなぁと。

例えば、MQTTサーバーから「ウイルスをダウンロードする」「コンピュータ内の全データを外部に送信する」「コンピュータ内の全データを削除する」といったPythonスクリプトがpayloadとして送られてきた場合、それをPythonのコードとして解釈して実行してしまうので、一発で詰みます。

2021-12-25 13:15 UTC, plmwa commented on main.py
>  client_id=""
globalにしてた時の名残です。消します

2021-12-25 13:19 UTC, Chaha1n commented on main.py
> +    if player_name!=eval(msg.payload.decode())["name"]:
ちなみに:
pythonで、JSON形式のstr→辞書型をやりたいときは、`json.loads(str)`が使えます。python3.6以上であれば、この関数の引数はbytes型でも構いません。

[参考](https://note.nkmk.me/python-json-load-dump/)

2021-12-25 13:20 UTC, Chaha1n commented on main.py
> +    if player_name!=eval(msg.payload.decode())["name"]:
あ、evalの意図を理解した。

2021-12-25 13:21 UTC, plmwa commented on main.py
> +    if player_name!=eval(msg.payload.decode())["name"]:
eval使わないほうがいいってでてきたので使わない方法考えます
{"name": "plmwa" ,"value",200}が辞書型じゃなくて一文の文字列として帰ってきたのでそれを再評価するためにeval使った

2021-12-25 13:24 UTC, Chaha1n commented on main.py
> +    if player_name!=eval(msg.payload.decode())["name"]:
bytes.decode()はbytes→strの変換やから仕方ないですね、json.loads()を使いましょう

2021-12-25 13:41 UTC, plmwa commented
レビュー見逃してた　.splitで書き換えました

2021-12-25 18:19 UTC, Chaha1n requested changes
# 重要！
**レビューを依頼した以上、コメントはしっかり読んでから実装してもらえると嬉しいです(答えは大体コメントに書いているつもりなので)**

2021-12-25 18:19 UTC, Chaha1n commented on main.py
>  def on_message(client, userdata, msg):
せっかくなので`user_data`のようにスネークケースを使いましょう！

2021-12-25 18:19 UTC, Chaha1n commented on main.py
> +    who_player=msg.payload.decode().split("\"")[3]
うーん、これもバグの原因になったり、変更に弱いのであまりやりたくないですね。
後からコードを読み直したとき/他人が読んだとき、`Object.name`なら「ああ、ここではname属性を読み取っているんだな」とすぐわかりますが、この実装だと「果たしてどの属性を受け取っているのだろう。送られてくるデータの形式を見直してみなくちゃ。」となって、バグの修正に手間がかかったり、読むのが面倒だったりするかなーと思います。(可読性の向上)

また、今回はあまり考えなくていいかもしれませんが、例えば、渡されるデータに新しい属性を足したいとなった場合、正しく受け取れなくなるかもしれないですよね。
一方で、bytes→辞書にする→キー("name")で取得する(`Object.name`のように)、という実装なら、オブジェクトにどれだけ新しい属性が増えようが、キーが変わらない限りは受け取れます。(変更に強い)

あとは、`who_player`という変数名も何を表しているのかわかりにくいかなと思います。
`player`という単語自体、playerの何を意味しているのか分かりにくいので、`player_name`としちゃうとか。
自分なら`received_player_name`?`parsed_player_name`?もっといい名前がありそうだけどそんな名前を付けるかなぁ。

長々と書いてきましたが、結局言いたいのは「実装をよく知らない人が読んでも、すぐに理解できるコードにしたい」ということです。この「よく知らない人」には、数日後の自分自身も含まれます。
良く言うのが「賢い実装」と「良い実装」は違う、ということです。
この実装は、一行で値の取り出しが済むので、「賢い」コードでしょう。でも、賢いがゆえに理解が難しく、結局「良い」実装よりも理解に時間がかかったり、些細なことで使えなくなったりします。

長くなりましたが、そんな感じでお願いしたいです。

2021-12-26 01:49 UTC, Chaha1n requested changes
あとちょっと！

2021-12-26 01:49 UTC, Chaha1n commented on main.py
> +    player_name_parsed_from_MQTT_payload=json.loads(msg.payload)
いま`player_name_parsed_from_MQTT_payload`に入っているのは
```
{
    "name":"plmwa",
    "value":"30"
}
```
のような辞書型ですから、`player_name`という名前はちょっと違う気がしませんか？`player_name_XXX.name`も少し違和感ありそう。

2021-12-26 02:55 UTC, Chaha1n approved these changes
L
G
T
M

2021-12-26 02:56 UTC, merged